version: '3'

services:
  redis-1001:
    image: redis
    container_name: redis-1001
    privileged: true
    ports:
      - 1001:6379
      - 11001:16379
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-1001/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /docker/redis/node-1001/data:/data
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.1
        
  redis-2001:
    image: redis
    container_name: redis-2001
    privileged: true
    ports:
      - 2001:6379
      - 12001:16379
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-2001/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /docker/redis/node-2001/data:/data
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.3
        
  redis-3001:
    image: redis
    container_name: redis-3001
    privileged: true
    ports:
      - 3001:6379
      - 13001:16379
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-3001/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /docker/redis/node-3001/data:/data
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.5
        
  redis-1002:
    image: redis
    container_name: redis-1002
    privileged: true
    ports:
      - 1002:6379
      - 11002:16379
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-1002/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /docker/redis/node-1002/data:/data
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.2
        
        
  redis-2002:
    image: redis
    container_name: redis-2002
    privileged: true
    ports:
      - 2002:6379
      - 12002:16379
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-2002/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /docker/redis/node-2002/data:/data
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.4
        
        
  redis-3002:
    image: redis
    container_name: redis-3002
    privileged: true
    ports:
      - 3002:6379
      - 13002:16379
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-3002/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /docker/redis/node-3002/data:/data
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.6
        
        
        
  sentinel-4001:
    image: redis
    container_name: sentinel-4001
    privileged: true
    ports:
      - 4001:26379
    restart: always
    depends_on:
      - redis-1001
      - redis-2001
      - redis-3001
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-4001/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-sentinel","/usr/local/etc/redis/sentinel.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.7
        
        
        
  sentinel-4002:
    image: redis
    container_name: sentinel-4002
    privileged: true
    ports:
      - 4002:26379
    restart: always
    depends_on:
      - redis-1001
      - redis-2001
      - redis-3001
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-4002/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-sentinel","/usr/local/etc/redis/sentinel.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.8
        
        
        
  sentinel-4003:
    image: redis
    container_name: sentinel-4003
    privileged: true
    ports:
      - 4003:26379
    restart: always
    depends_on:
      - redis-1001
      - redis-2001
      - redis-3001
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /docker/redis/node-4003/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    sysctls:
      net.core.somaxconn: '511'
    command: ["redis-sentinel","/usr/local/etc/redis/sentinel.conf"]
    networks:
      redis-cluster-net:
        ipv4_address: 10.10.10.9
        
        
networks:
    redis-cluster-net:
      driver: bridge
      ipam:
        config:
          - subnet: 10.10.10.0/16